### ISSUE TITLE
Could we have more examples?

### ISSUE THREAD

**Issue by iddm** [MegaLoler/lispcord#22]
The library is awesome. I am learning common lisp at this moment and I like to learn something by doing real-life tasks. Now I want to code a bot for the discord. Could we have more examples? Or can we have a library API documentation so we know what to call when we need to do something? Thanks!

**Comment by spreadLink** [comment]
Thank you :) 
Which branch are you on? The master-branch is outdated atm, and work on the depipe one isn't going as quickly as i'd like, but it's still more complete than the master branch so i'd advise on using that instead. 
Do you have any ideas on what else to do examples for?

As for documentation, i do intend to actually fix the docs eventually but writing docs is a pain so <.<'

**Comment by spreadLink** [comment]
I updated the Documentation at https://lispcord.github.io/
Unfortunately it is still incomplete and quite ugly, but maybe you find some useful stuff there.

**Comment by iddm** [comment]
I am looking forward seeing `depipe` merged into `master` branch. But I was unable to run the bot with `depipe` branch, there were some strange errors. Also, the thing you say about the documentation are true :) I have read your code and understand it fully anyway (because of LISP or anything else, don't know), but the docs are nice-to-have I think :) Thanks for the link :)

About the examples: having `ping` example is must-have and thanks for creating it. I'd provide just a bit more documentation into it. I am coming with a big `Rust` usage and you know, the docs there are.... the worlds best docs ever. For example, you may look at examples of [this rust library](https://github.com/zeyla/serenity/tree/master/examples) and how much examples are there. Or you may look at how [the docs detailed are](https://docs.rs/serenity/0.5.1/serenity/). Reading such docs or examples makes 100% understanding of the library immediately. I like the `lispcord` but I think it would be nice to provide such kind of understanding for new users of this package.

**Comment by spreadLink** [comment]
Now, i do agree that we need better documentation.
But the reason that serenity needs so many examples is because it is a significantly more complex library for a significantly more complex language.
Except for the Ping-bot, none of the examples in concept apply to lispcord, as it doesn't require any fancy interaction with the process-environment, or needs a command-framework or a message-builder.

I did however add another example in the examples folder which showcases how a primitive command system may be structured. I hope it helps :+1: 

Also, please make sure you are on the latest branch of depipe and post issues for any weird errors. I have verified the current branch works without issue with the examples on my machine so it may be portability issues or w/ever. Thanks you for your help :smile:

**Comment by spreadLink** [comment]
Oh ye also, as long as you don't have any more requests for specific examples I'll mark this as closed
