### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by naryl** [MegaLoler/lispcord#44]
My previous commit left the repo in a non-buildable state. Of course I'll try to avoid it in the future but Travis CI integration will help catch these issues a lot faster. I can set it up myself, just need the approval of the organization owner to give it read access to the repo.

**Comment by naryl** [comment]
@spreadLink @MegaLoler I hope you didn't forget about lispcord. :)

**Comment by spreadLink** [comment]
I didn't, but i'm confused how this even happens.

Lispcord is supposed to be written in portable CL, reloading the project before a push should be all that's required.
Adding a third party monitoring system is completely overkill

**Comment by naryl** [comment]
Writing it in portable CL doesn't make it 100% portable. https://github.com/lispcord/lispcord/blob/730d18c72514301b9d1cb4683885685d893a9276/src/lispcord.lisp#L38

There were a lot of issues with CCL build too and adding a third party monitoring system is less of an overkill than reloading the project in three implementations (There's no hope for CLisp) manually before each push.

**Comment by spreadLink** [comment]
I didn't want to post this publicly here, but you seem to have blocked me on discord (why?) so i have no other way of communication.

Excuse me but why did you disable that line on the two implementations without adding an alternative?
You are aware that sanitize-string is supposed to remove mentions etc. right? How is it supposed to do that on ccl here? And why would it fail on CCL anyway, substitute is a standard library function; If the issue is the Unicode-naming (which might well be for all i know), wrap that expression into the compile exclusion and provide an alternative. Don't just silently break the API of the library.

Furthermore, many of the class changes in the referenced commit (OR NULL)s a lot of fields that should not be null.
For example, the reaction class (https://discordapp.com/developers/docs/resources/channel#reaction-object) should _not_ have a null count or emoji field ever. The json-deserialiser function should handle those cases instead. Please keep the class definitions themselves as close to the discord api docs as possible. 

Lastly, i don't understand how the inline declarations would be problematic on CCL. The commit messages are not enlightening me in this regard unfortunately.

I'm categorically against increasing the complexity of any project beyond what is really required.
Travis CI, or any external build tool, is complexity added that could be solved through a simple shell or bash script, or even a lisp file if you want. How does adding it provide value beyond that?

**Comment by naryl** [comment]
Uh... I couldn't have blocked you on Discord because I'm pretty sure we didn't ever talk there. I tried to find either spreadLink or MegaLoler on the Lisp guild but couldn't. The only other person who talked about lispcord (other than trying it out) was "ein Strauch". I didn't block him/her/it. Well, I didn't block anyone from that guild.

> You are aware that sanitize-string is supposed to remove mentions etc. right?

It's a function which only replaces one character with another. It's not used anywhere in the library and no docs or examples mention why a user would want to use it. There's no documentation string either. The character it replaces is unknown to either ecl or ccl. Removing mentions is performed by `remove-mention`: https://github.com/lispcord/lispcord/blob/730d18c72514301b9d1cb4683885685d893a9276/src/lispcord.lisp#L70

If sanitize-string is supposed to remove mentions etc then I wasn't aware of that and I don't see anything in the code that could have made me aware of that. It clearly was not doing what it was supposed to do before I touched it either.

> Furthermore, many of the class changes in the referenced commit (OR NULL)s a lot of fields that should not be null.

Sorry about this one. Discord has a few errors in the docs so I thought that's among them too. It says that the fields can't be null, yet gateway sent objects without these fields. I'll review all class definitions and decide what to do when Gateway's behaviour actually differs from the docs on per-case basis.

> Lastly, i don't understand how the inline declarations would be problematic on CCL

They won't. CCL complained specifically about `inline` declaration. I realized a commit later that the problem was because the symbol is `lispcord.classes:inline` instead of `common-lisp:inline`. Inlining these functions never worked on SBCL either but it didn't complain for some reason.

> I'm categorically against increasing the complexity of any project beyond what is really required.

It's arguable whether a script or Travis CI integration is more complex from the project's point of view, so it's for you to decide. I got it, your choice is a script with a git pre-push hook. I'll do it to close this issue.

**Comment by naryl** [comment]
Btw we should really mention which implementations Lispcord aims to support and what it aims to be.

> Lispcord aims to make it freakishly easy to build bots for Discord.

It lacks a lot of things to make it freakishly easy to build bots. At this point it looks like Gateway protocol implementation and HTTP API wrapper and is almost the simplest thing it can be to implement just that.

EDIT: Almost, because it has a few random utility functions thrown in.

**Comment by naryl** [comment]
Wait, you can't just put a pre-push hook into the repo. And that would also require all contributors to have all supported implementations. OTOH it will find build errors before push, not after. By now I think Travis CI is actually the less complex way (assuming it won't disappear). The only even less complex way is to declare that we only support SBCL.

**Comment by spreadLink** [comment]
yes, ein Strauch is my discord handle, and i cannot message nor add you as a friend, and discord blocks all information about you on my side (like, for example, shared servers etc.)
It usually only does that when you are blocked.

`remove-mention` removes a specified user from the message.
`sanitize-string` is supposed to be used in the bot, to remove _the concept_ of mentioning by removing any @-signs.
This is supposed to be an easy, lazy, for-testing way to quickly make commands like `say` without turning the bot into a mention-bomb.
As far as the symbol not being known to CCL, it is a standard unicode character (https://www.fileformat.info/info/unicode/char/1f47d/index.htm), and CCL claims to have full unicode support (https://ccl.clozure.com/docs/ccl.html).
Therefore, this is a bug in CCL and not a compatibility issue on our end, but working around it is still fine until it is fixed. If you could find a different, equivalent in spirit (i.E. being whimsical and obvious) symbol, that'd be okay. 

For the discord docs, ye they are horrid, and if we need to diverge to make the lib work, that's okay, but things like non-nullable fields being null should (imo) be handled in the constructor.
Deciding on a case-by-case basis is fine as well.

The inline stuff is bizarre to me. lispcord `:use`s cl so i don't understand how we overwrote the symbol.

Lispcord is supposed to be written in standard CL, but is limited by the libraries it pulls in. So in practice we should support the overlap of all the implementations the dependencies support (which, at the moment, i believe is SBCL and CCL from w-d)

What is or is not freakishly easy i suppose depends on the person. For example, lispcord used to have a (internally) complex pipe system that let you configure bots as if they were streams, but it wasn't nice and replaced with an easier system.
For me, i'd say having the library get out of the way as much as possible and not enforce any special conventions or force certain ways of programming as much as possible, is easy.
To me, frameworks do exactly that, tho, and hence i tried to avoid that.
But that is a philosophical debate really.

As for pre-push hooks, i'd consider that to be too complex as well. I'd literally just use a shell script, simply because i'd not use a utility in lispcord that's not documented in CLHS (plus unicode), so testing over multiple implementations should not be needed.
Issues that arise with other implementations, then, are either issues of the underlying libraries, or those implementations (see the unicode issue above).

Lastly, i want to note that lispcord never got the love it really deserves, as i unfortunately ran out of time to work on it properly too quickly. I'm fairly glad that you are taking over here, we just have to work out the philosophical differences here i suppose :)

**Comment by naryl** [comment]
We discussed the rest in Discord, so relevant to this issue:
> i'd not use a utility in lispcord that's not documented in CLHS (plus unicode), so testing over multiple implementations should not be needed. Issues that arise with other implementations, then, are either issues of the underlying libraries, or those implementations.

Yep. Sadly, we still have to catch them because our usage of these libraries may be what triggers the incompatibility bug.

And I just thought of something. Dithcord uses Travis CI so if Lispcord has any build issues they'll be found through Dithcord. Lispcord doesn't have any tests and about 90% of its functionality is not easily testable so it defeats half of CI's purpose. The only thing we really lose is automatically building PRs, but I guess if they build for [the contributor's default implementation] then it's not a big deal that incompatibilities are found later.

**Comment by spreadLink** [comment]
👍
