### ISSUE TITLE
How do I run the bot in example-bot?

### ISSUE THREAD

**Issue by ghost** [MegaLoler/lispcord#58]
I'm using SBCL 2.2.9.debian and I'm really new to the whole asd thing, I tried:
```
sbcl --load "example-bot.asd"

* (ql:quickload :lispcord) 
* (ql:quickload :example-bot)
* (example-bot:main)

debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {1001368073}>:
  The symbol "MAIN" is not external in the EXAMPLE-BOT package.

    Stream: #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001B4F3}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Use symbol anyway.
  1: [ABORT   ] Exit debugger, returning to top level.

(SB-IMPL::READ-TOKEN #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001B4F3}> #\e)
```
I'm not sure what I'm supposed to run and I'm not really getting lucky with searching related things up.
I am sorry if this isn't the right place or it is something really obvious

**Comment by spreadLink** [comment]
The problem here is on your last line: `(example-bot:main)`; the `main` there is not exported by the example-bot package. You can either `(in-package :example-bot)` to enter the package, then run `(main)`, or break package privacy by running `(example-bot::main)` (note the two `:` instead of just one).

In a proper project, you'd probably want to export `main` in the package definition as usual, but I didn't bother with it in the example.
